import Head from 'next/head'

const IndexPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className='text-blue-400'>テスト</h1>
    </>
  )
}

export default IndexPage